#!/bin/bash

echo
echo 'Installing QtChat...'

# Build the application
echo
echo '-------------- Building QtChat'
echo

make -C ./src

if [ $? != 0 ]; then
  echo
  echo '===================== Failed building application!'
  echo
  echo 'Exiting...'
  echo
  exit 1
fi

# Clean up after build
if [ "$1" == "-c" ]; then
  echo
  echo '-------------- Cleaning'
  echo

  rm src/*.o
  rm src/moc*
fi

if [ -e './QtChat' ]; then
  rm ./QtChat
fi

# Retrieve the executable from the compiling directory
mv ./src/QtChat ./QtChat

if [ $? != 0 ]; then
  echo
  echo '===================== Failed fetching application!'
  echo
  echo 'Exiting...'
  echo
  exit 1
fi


# If all went well, exit cleanly
echo
echo "Done!"
echo

exit 0
